remote_theme: mmistakes/minimal-mistakes@4.24.0

title: "Bioinformatics Projects — Ipek Selcen"
description: "Reproducible analysis templates and notes."

plugins:
  - jekyll-include-cache
  - jekyll-feed     
  - jekyll-sitemap

# optional header link back
