title: "Ipek Selcen - Bioinformatics Projects"
description: "Bioinformatics"
url: "https://ipekselcen.github.io"  
baseurl: "/bioinformatics-projects"    

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "default"

defaults:
  - scope: { path: "" }
    values:
      layout: single
